<a href="https://colab.research.google.com/github/sans0726/100-days-of-deep-learning/blob/main/GRU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Input at current time step
x_t = np.array([[0.5],
                [0.2]])

# Previous hidden state
h_prev = np.array([[0.1],
                   [0.3]])

# GRU weights
W_z = np.random.randn(2, 2)
U_z = np.random.randn(2, 2)
b_z = np.zeros((2, 1))

W_r = np.random.randn(2, 2)
U_r = np.random.randn(2, 2)
b_r = np.zeros((2, 1))

W_h = np.random.randn(2, 2)
U_h = np.random.randn(2, 2)
b_h = np.zeros((2, 1))


def sigmoid(x):
    return 1 / (1 + np.exp(-x))


# 1. Update gate
z_t = sigmoid(
    W_z @ x_t +
    U_z @ h_prev +
    b_z
)

# 2. Reset gate
r_t = sigmoid(
    W_r @ x_t +
    U_r @ h_prev +
    b_r
)

# 3. Candidate hidden state
h_candidate = np.tanh(
    W_h @ x_t +
    U_h @ (r_t * h_prev) +
    b_h
)

# 4. New hidden state
h_t = (1 - z_t) * h_prev + z_t * h_candidate


print("Update gate:")
print(z_t)

print("\nReset gate:")
print(r_t)

print("\nCandidate hidden state:")
print(h_candidate)

print("\nNew hidden state:")
print(h_t)

Update gate:
[[0.7839683 ]
 [0.44727607]]

Reset gate:
[[0.38294324]
 [0.62738036]]

Candidate hidden state:
[[0.40963781]
 [0.55829724]]

New hidden state:
[[0.34274623]
 [0.41553017]]
