<a href="https://colab.research.google.com/github/sans0726/100-days-of-deep-learning/blob/main/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Input sequence
X = np.array([1.0, 2.0, 3.0])

# Target sequence
Y = np.array([2.0, 4.0, 6.0])

print("X:", X)
print("Y:", Y)

X: [1. 2. 3.]
Y: [2. 4. 6.]


In [ ]:
np.random.seed(42)

input_size = 1
hidden_size = 3
output_size = 1

# RNN parameters
W_xh = np.random.randn(hidden_size, input_size) * 0.1
W_hh = np.random.randn(hidden_size, hidden_size) * 0.1
b_h = np.zeros((hidden_size, 1))

# Output layer
W_hy = np.random.randn(output_size, hidden_size) * 0.1
b_y = np.zeros((output_size, 1))

print("W_xh:\n", W_xh)
print("\nW_hh:\n", W_hh)
print("\nW_hy:\n", W_hy)

W_xh:
 [[ 0.04967142]
 [-0.01382643]
 [ 0.06476885]]

W_hh:
 [[ 0.15230299 -0.02341534 -0.0234137 ]
 [ 0.15792128  0.07674347 -0.04694744]
 [ 0.054256   -0.04634177 -0.04657298]]

W_hy:
 [[ 0.02419623 -0.19132802 -0.17249178]]


In [ ]:
h_prev = np.zeros((hidden_size, 1))

hidden_states = []
outputs = []

for t in range(len(X)):

    x_t = np.array([[X[t]]])

    # Hidden state
    h_t = np.tanh(
        W_xh @ x_t +
        W_hh @ h_prev +
        b_h
    )

    # Output
    y_t = W_hy @ h_t + b_y

    hidden_states.append(h_t)
    outputs.append(y_t)

    h_prev = h_t

print("Outputs:")

for t, y in enumerate(outputs):
    print(f"t={t}: {y.flatten()}")

Outputs:
t=0: [-0.00731041]
t=1: [-0.01515192]
t=2: [-0.0230725]


In [ ]:
loss = 0

for t in range(len(X)):
    target = Y[t]
    prediction = outputs[t][0, 0]

    loss += 0.5 * (prediction - target) ** 2

print("Loss:", loss)

Loss: 28.214071142630537
